### ISSUE TITLE
save! fails silently with unique indexes

### ISSUE THREAD

**Issue by chadrem** [mongomapper/mongomapper#166]
http://gist.github.com/282556 demonstrates the problem.  In summary, I create new documents and save both of them.  Both save! method calls return true, but only the first one actually saved.  The second one fails silently.  Lines 28, 30, and 34 demonstrate the problem.  Lines 45 - 63 show the indexes (created by calling MongoMapper.ensure_indexes!).

**Comment by smtlaissezfaire** [comment]
Another option is to use safe in your model:

module User
  safe
end

(see safe.rb in the examples directory)
