### ISSUE TITLE
mongo_mapper 0.8.6 require i18n 0.7.0 now

### ISSUE THREAD

**Issue by solisoft** [mongomapper/mongomapper#626]
Hi, I'm trying to configure a server for a very old app I have ...
I did use mongo_mapper 0.8.6 and in my running server I can see that i18n gem used is 0.6.0 (which works fine with ruby 1.8.7) 

Now it looks like mongo_mapper 0.8.6 needs i18n 0.7.0 ... but it fail because I use ruby 1.8.7 and require ruby 1.9.3 ...

Any idea?

**Comment by smtlaissezfaire** [comment]
Not sure on this issue but MM 0.8.6 is super out of date.  I'm going to close this one.
