### ISSUE TITLE
Plugin instance methods in 0.13.1?

### ISSUE THREAD

**Issue by DGaffney** [mongomapper/mongomapper#643]
The documentation here: http://mongomapper.com/documentation/plugins/ is either out of date or I'm interpreting the use wrongly: 

```ruby
require 'mongo_mapper'
module ActsAsListFu
  extend ActiveSupport::Concern

  included do
    key :position, Integer, :default => 1
  end

  module ClassMethods
    def reorder(ids)
      # reorder ids...
    end
  end

  module InstanceMethods
    def move_to_top
      puts "HEY"
    end
  end
end
class Item
  include MongoMapper::Document
  plugin ActsAsListFu
end
MongoMapper::Document.plugin(ActsAsListFu)
Item.new.move_to_top
```

Try the above in irb using MM 0.13.1 - seems to fail? Am I using it wrongly or is something screwy here?

**Comment by DGaffney** [comment]
Looking at this further, this code works in 0.12.0 - Running the above code in that version yields a deprecation notice about the problem I'm seeing now: "DEPRECATION WARNING: The InstanceMethods module inside ActiveSupport::Concern will be no longer included automatically. Please define instance methods directly in ActsAsListFu instead." Therefore, the code displayed on http://mongomapper.com/documentation/plugins/ should now read as follows:

```ruby
require 'mongo_mapper'
module ActsAsListFu
  extend ActiveSupport::Concern

  included do
    key :position, Integer, :default => 1
  end

  def self.reorder(ids)
    # reorder ids...
  end

  def move_to_top
    puts "HEY"
  end
end
class Item
  include MongoMapper::Document
  plugin ActsAsListFu
end
MongoMapper::Document.plugin(ActsAsListFu)
Item.new.move_to_top
```

**Comment by smtlaissezfaire** [comment]
Thanks @DGaffney + @jcaudle. Closing this.
