### ISSUE TITLE
Support for mongoldb 3.4

### ISSUE THREAD

**Issue by kerby82** [mongomapper/mongomapper#651]
Mongo mapper it is not compatible with mongodb 3.4.

Because it depends on mongo gem ~> 1.8 which does not support mongodb 3.x

Is there a way to enable the support with mongo 3.x?

**Comment by jamieorc** [comment]
There was some work being done by a contributor or two, but it's never been finished.

**Comment by smtlaissezfaire** [comment]
Fixed in 0.15.0
