### ISSUE TITLE
sinatra installtion instructions out of date

### ISSUE THREAD

**Issue by timolehto** [mongomapper/mongomapper#652]
These instructions do not work:
http://mongomapper.com/documentation/getting-started/sinatra.html

The required gems to run mongo_mapper with sinatra seems to be:
```
gem 'sinatra'
gem 'activemodel-serializers-xml'
gem 'active_model_serializers'
gem 'mongo_mapper'
gem 'bson_ext' #well, sort of optional but highly recommended
```

**Comment by smtlaissezfaire** [comment]
Yes, I noticed these recently too.  

Do you need `gem 'active_model_serializers'` if you have `gem 'activemodel-serializers-xml'`?

**Comment by smtlaissezfaire** [comment]
Also, this is only for rails 5.  Is there a way we can conditionally do this based on what rails is loaded?

**Comment by kwicher** [comment]
I installed all gems but when I try to require 'activemodel-serializers-xml' I am getting
/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- activemodel-serializers-xml (LoadError)

Any ide whyy

**Comment by smtlaissezfaire** [comment]
Not sure off hand, but I believe this is related: https://github.com/rails/rails/issues/24558

**Comment by kwicher** [comment]
It probably does relate but still the suggestions there do not solve the problem.

**Comment by kwicher** [comment]
Interestingly when using Bundler with"
`gem "sinatra"
gem "activemodel-serializers-xml"

gem "active_model_serializers"

gem "mongo_mapper"

gem "bson_ext"
`
and then requiring only Sinatra and mongo_mapper

Everything is OK

**Comment by smtlaissezfaire** [comment]
Closing this - please reopen if you are still seeing it.

Should be OK now with:

```
gem 'sinatra'
gem 'mongo_mapper'
```
