### ISSUE TITLE
Model key with name "attributes" not works

### ISSUE THREAD

**Issue by pavelvasev** [mongomapper/mongomapper#657]
Hi MongoMapper team!

Please explain, `attributes` is a valid name for key or not?

If yes, could you please complain about that to stderr/stdout while you see user tries to create such attribute? We spending a lot of time founding why our app not working with such key name.. 

```
class Point
  include MongoMapper::Document
  key :name_id, ObjectId
  key :value, Float
  key :attributes, Hash, {}
...
end
```
Thank you!

**Comment by smtlaissezfaire** [comment]
Thanks for the bug report.

Yes - `attributes` is the method used in ActiveModel / ActiveRecord to get a hash from the object.  Usually `#attributes=` will take a hash and assign each key.  I definitely wouldn't use it!   :) 

Will write a test + raise an error for this.  Thanks for reporting!
